{% set name = "nslsii" %}
{% set version = "0.0.12" %}
{% set sha256 = "16caf1024fb6b1401a9b8b97590635fb58531ba0b231a769b5d471a70d4a72bf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -v"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bluesky
    - caproto
    - databroker
    - ipython
    - ipywidgets
    - matplotlib
    - numpy
    - ophyd
    - psutil
    - pyolog

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/NSLS-II/nslsii
  license: BSD
  license_file: LICENSE
  summary: Repository of tools used for both data collection and analysis at NSLS-II.
