{% set name = "nslsii" %}
{% set version = "0.1.0" %}
{% set sha256 = "6cca2625b306af14a8a04459fd14fc4130cffca90297fb5cee31336946a4d74b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -v

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - bluesky
    - bluesky-kafka
    - caproto
    - databroker
    - ipython
    - ipywidgets
    - matplotlib
    - numpy
    - ophyd
    - psutil
    - pyolog

test:
  imports:
    - nslsii

about:
  home: https://github.com/NSLS-II/nslsii
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Repository of tools used for both data collection and analysis at NSLS-II.
