{% set name = "nslsii" %}
{% set version = "0.1.1" %}
{% set sha256 = "adc4a3cf4f59bb109e0294141386cf3e5ebed4d6041880c301837079f7544438" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - bluesky
    - bluesky-kafka
    - caproto
    - databroker
    - ipython
    - ipywidgets
    - matplotlib
    - numpy
    - ophyd
    - psutil
    - pyolog

test:
  imports:
    - nslsii

about:
  home: https://github.com/NSLS-II/nslsii
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Repository of tools used for both data collection and analysis at NSLS-II.
