{% set name = "nslsii" %}
{% set org = "NSLS-II" %}
{% set sha256 = "9aa3c4881e9b66cb6042369855489e3355a9c10acb7c6bef4897a834c1b47078" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -v"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bluesky
    - caproto
    - databroker
    - ipython
    - ipywidgets
    - matplotlib
    - numpy
    - ophyd
    - psutil
    - pyolog

test:
  imports:
    - {{ name }}
about:
  home: https://github.com/{{ org }}/{{ name }}
  license: BSD
  license_file: LICENSE
  summary: Repository of tools used for both data collection and analysis at NSLS-II.
