{% set name = "nslsii" %}
{% set org = "NSLS-II" %}
{% set version = "0.0.10" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    git_url: https://github.com/{{ org }}/{{ name }}
    git_rev: v{{ version }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True  # [py2k]

requirements:
    build:
        - python
    run:
        - bluesky
        - caproto
        - databroker
        - ipython
        - ipywidgets
        - matplotlib
        - numpy
        - ophyd
        - psutil
        - pyolog
        - python

test:
    imports:
        - nslsii

about:
    home: https://github.com/{{ org }}/{{ name }}
    license: BSD
